alias .. "cd .."
alias g "hub"
alias git "hub"

alias pyg "pygmentize"
alias n "nvim"
alias v "vim"

alias ls "exa"
alias la "exa -a"
alias ll "exa -l"
alias l "exa -al"

alias cleanplug "rm -rf ~/.local/share/nvim/plugged ~/.config/coc"

alias brewup "brew update && brew upgrade"

alias cleanview "rm -rf ~/.local/share/nvim/view ~/.vim/view"
alias cleann "rm -rf ~/.local/share/nvim/view"
alias cleanv "rm -rf ~/.vim/view"

alias npmlist "npm list --depth 0"
alias npmlistg "npm list -g --depth 0"

alias ea "n ~/.config/fish/aliases.fish"
alias ec "n ~/.config/fish/config.fish"
alias en "n ~/.config/nvim/init.vim"
alias ev "v ~/.vimrc"
alias eb "n ~/.vim/basic.vim"
alias ef "n ~/.vim/full.vim"

# git aliases
alias gcl "git clone"
alias ga "git add"
alias gaa "git add -A"
alias gb "git branch"
alias gcam "git commit -a -m"
alias gcams "git commit -a -S -m"
alias gco "git checkout"
alias gcb "git checkout -b"
alias gcm "git checkout master"
alias gcd "git checkout develop"
alias gd "git diff"
alias gf "git fetch"
alias gfa "git fetch --all --prune"
alias gfos "git fetch origin"
alias gpl "git pull"
alias glog "git log --oneline --decorate --graph"
alias glogo "git log --color --all --date-order --decorate --dirstat=lines,cumulative --stat"
alias gm "git merge"
alias gps "git push"
alias gpsom "git push origin master"
alias gsb "git status -sb"
alias gst "git status"
