alias g "hub"
alias git "hub"

alias n "nvim"
alias v "vim"

alias ea "n ~/.config/fish/aliases.fish"
alias ec "n ~/.config/fish/config.fish"
alias en "n ~/.config/nvim/init.vim"
alias ev "v ~/.vimrc"

# git aliases
alias ga "git add"
alias gaa "git add -A"
alias gb "git branch"
alias gcam "git commit -a -m"
alias gco "git checkout"
alias gcb "git checkout -b"
alias gcm "git checkout master"
alias gcd "git checkout develop"
alias gd "git diff"
alias gsb "git status -sb"
alias gst "git status"
alias gf "git fetch"
alias gfa "git fetch --all --prune"
alias gfos "git fetch origin"
alias gl "git pull"
alias glog "git log --oneline --decorate --graph"
alias gm "git merge"
alias gp "git push"
